name: Build packages

on:
  push:
    tags: "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        os:
        - linux
        - darwin
        arch:
        - amd64
        - arm64
        exclude:
        - os: darwin
          arch: arm64

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.1' # The Go version to download (if necessary) and use.
    - name: build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        make pkg
        cd _packages && for var in $(ls); do sudo bash -c "echo $(sha256sum $var | awk '{print $1}') > $var.sha256"; done && cd -
    - uses: actions/upload-artifact@v2
      with:
        name: wormhole
        path: _packages
    - uses: Rory-Z/upload-release-asset@v1
      if: github.event_name == 'release'
      with:
        repo: wormhole
        path: "_packages/wormhole-*"
        token: ${{ github.token }}

  build_docker:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: build docker
      run: make docker
    - name: push docker
      if: github.event_name == 'release'
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
        docker push emqx/agent:$(git describe --tags --always)
